name: Manual NPM Install

# This sets up manual triggering through the GitHub Actions UI
on:
  workflow_dispatch:
    # You can add input parameters here if needed later
    # inputs:
    #   example_input:
    #     description: 'Example input parameter'
    #     required: false
    #     default: 'default value'

jobs:
  install:
    name: Run npm install
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install

      - name: Run bidara
        run: npm run dev